### ISSUE TITLE
contract error line 40:45

### ISSUE THREAD

**Issue by obo182** [junbest/Pancakeswap_bot#1]
pancake.sol:40:45: ParserError: Expected ';' but got '{'
uniswapRouter.swapExactETHForTokens {value: ethBalance}({amountOutMin: minTokens, path: paths, to: _uni, deadline: deadline});
^

**Comment by junbest** [comment]
hi sorry for late reply, use the 0.6.12 version of compiler

**Comment by junbest** [comment]
solve
